### ISSUE TITLE
add/edit places

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#1]
As a data editor, I want to add or edit a place and associate it with a GeoNames ID so that I can link books and people to places that can be plotted on a map.

**Comment by christianflow** [comment]
I tested this by going to "Places" and adding Rochester, New York to the places. It not only added Rochester to the line-up, but also allowed me to search for the place with a GeoNames ID, such that it appeared on the associated cartographic display. Very satisfied with this.
