### ISSUE TITLE
edit book - book/person interactions

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#11]
As a data editor, when I’m editing a book I want to document the people who interacted with it in ways other than annotation so that I can track which books they owned, read, etc.

**Comment by christianflow** [comment]
This works nicely. I added several people and their modes of interaction to a couple of different books, with great success. Then I created a person (Jimbo Fisher) and added him as an interactor. One thing that would be helpful is if we could make the list of persons that shows up in the field of interactors display by alphabetical order, not by when people were asked (Jimbo was not added in "J" but rather at the very bottom).
