### ISSUE TITLE
book search fields

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#16]
As a data editor, when I search for books in the admin interface I want to search on title, author, call number, publisher name and notes so that I can find specific items.

**Comment by jmrampling** [comment]
Searched for Paracelsus, Baderbuchlin (one of the most signfiicant items in the collection, which is included in the database using those spellings) and found 0 results. Has book failed to export, or is there an issue with the spelling of search terms?

**Comment by jmrampling** [comment]
It isn't clear how the list of short titles is organized. Under "Books," they do not appear to be organized alphabetically, numerically by date or Win number, or any other system. Can we discuss how this information is arranged?

**Comment by christianflow** [comment]
We searched for "oz" in title and received in the search results, in addition to The Wizard of Oz (which we had added to the list, and which represented a good search result), two other books that boasted the conjucture -oz- in the author name, e.g. As search results, these are not particularly helpful.

**Comment by rlskoeser** [comment]
@jmrampling the data import script currently has an issue with _Congeries Paracelsica_ (I think because it has no date), is that the title you mean?  See my notes on #31 for the question and list of errors.

I'm setting a default sort based title as per your feedback in #14.  Let me know if this should be something else or if you want multiple fields included in the default sort.

Now that I'm looking more, I see that not all volumes have short titles.  Should I display full titles in the browse list instead?  Or should the data import script truncate full titles to set a short title if one is not present?

@christianflow think of the Django admin search as a quick and dirty search to help you get to the record you want to work on.  It's doing a partial match on _any_ of the fields that we specified should be searched, so if "oz" occurs anywhere as part of a name, title, publisher, etc, a record is going to show up.  When we build the public, user-facing search we'll spend more time tuning it and making sure it behaves the way you want and expect it to, but for this we just need something that will let you edit and work with the data.

**Comment by christianflow** [comment]
Now that we fixed the spreadsheet for the purposes of the new import, Baderbuchlin shows up perfectly in the search. Apologies for this, Rebecca and Ben, for the problem was really ours (the information had not been curated appropriately in the sheet so as to allow import). Search seems to me to work quite well, and should be more than sufficient for the purposes of editing/admin. When we go to do the user-facing search we might be able to talk more about ways to tweak to give perfect search results (e.g. with U vs V interchangeable). But this looks great. Many thanks!
