### ISSUE TITLE
add/edit person relationship types

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#19]
As a data editor, I want to add a new or edit an existing relationship type so that I can document the kinds of relationships between people associated with the project.

**Comment by bwhicks** [comment]
Question: Do we want to do this only inline through relationship (which is inline to person per another Git issue) or should it still be a separate field in the main admin? I assume the latter, but wanted to clarify before I make changes.

**Comment by rlskoeser** [comment]
@bwhicks I think it would be helpful and more clear to have direct access to the relationship types in the admin.  E.g., if they discover a whole group of relationship types they didn't thin of adding before, it will be much easier to add them that way.

**Comment by bwhicks** [comment]
@rlskoeser Great, that's how I left it when I pushed.

**Comment by christianflow** [comment]
Added a few more relationship types and found that they were entered smoothly and could be deployed as classifications. Wonderful feature, because we will surely discover other types of relationships as we go.
