### ISSUE TITLE
edit places - geonames lookup

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#2]
As a data editor, when I’m editing a place I want to be able to look up the GeoNames ID by name and select from suggestions so that I can select the appropriate name within the system.

**Comment by christianflow** [comment]
Checked this by searching for Munich: several locales in the neighborhood were offered to me as options, from which I chose Unterschliessheim, much to my satisfaction. It both showed on the map and was entered into the list successfully.
