### ISSUE TITLE
edit person - view related people

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#21]
As a data editor, when I’m editing a person I want to view a list of people who are related to the current person so I can compare relationships.

**Comment by rlskoeser** [comment]
Note: this is intended to provide a read-only list of the relationships _to_ the current person (as opposed to the _from_ relationships that are editable on the form), as a way to provide other information and provide a sanity-check on symmetric or related relationships.

It would be very convenient to have related person names linked to the person edit page - see https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#reversing-admin-urls

Suggested layout - adjust from-relationships edit form inline to display:
current person | relationship | related person | dates | notes
(where current person name is repeated for every row and not editable)

Then adapt or mimic that layout to display the reverse relationships in the same format:
related person | relationship | current person | dates | notes

**Comment by rlskoeser** [comment]
For the inline, seems like it should work to customize the inline template for just that form and add the current object as the first row in the table.

**Comment by christianflow** [comment]
This is a great feature, and it works well: I have tested it by affiliating people and books to see them displayed in the person-edit form. One thing I would note is that for the books it seems to be displaying their full title, which makes for an awfully long line. Might be better to make the move to "short title," which we'll eventually get in order. Thanks Ben!
