### ISSUE TITLE
edit person - autopopulate data from VIAF

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#23]
As a data editor, when I edit a person and add or change the VIAF ID, I want the birth and death dates and sex in the system populated from data available in VIAF in order to make data entry more efficient.

**Comment by bwhicks** [comment]
A functionality note: Setting the VIAF for a person will blank their birth and death dates. They'll then be supplied by VIAF on save if they exist.

This also applies to imports from the spreadsheet (#31), although there are other issues with the script to sort before it can be delivered for testing.

**Comment by christianflow** [comment]
I changed the name Agricola, Johannes to Kepler, Johannes. Then input "Johannes Kepler" into the viaf id, located it in the pulldown menu, hit "Save and continue editing" and noted that it updated the birth- and death-dates accordingly.
