### ISSUE TITLE
person list fields

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#25]
As a data editor, when I’m viewing the list of people I want to see authorized name, sort name, birth and death dates, viaf id, and family group so that I can quickly get a sense of the records I’m looking at.

**Comment by bwhicks** [comment]
Will add birth and death date fields once model is updated.

**Comment by rlskoeser** [comment]
I went ahead and adding birth/death to the list view while I was adding them - don't know if anything else needs to be done here, so I'll hold of marking it as dev complete.

**Comment by christianflow** [comment]
Looks good!
