### ISSUE TITLE
person list filter fields

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#26]
As a data editor, when I’m browsing the list of people I want to filter by family group so that I can quickly look at a particular group of people.

**Comment by christianflow** [comment]
This looks good. Family group is going to be something that gets more important down the road when we add books from other collections. We might eventually want to think too about separating "People of Interest" (i.e. players that interacted with the books) from mere "Persons" (vel sim): i.e., people like authors who really aren't going to have relationships with other people by and large or do things themselves. That is just something to keep an eye on for now.
