### ISSUE TITLE
data import

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#31]
As a data editor, I want a one-time import of books (with associated people, places, publishers, and NYSL cataloguing information) from spreadsheet data into the system so that I can refine and augment the initial person data that’s already been collected.

Clean up to be done:

- [x] publishers and author names include variants with and without trailing periods; strip spaces and periods before looking for a match and importing names.
- [x] Don't create records for publishers or people where name is just `?` or an empty string
- [x] Support longer titles

**Comment by rlskoeser** [comment]
Discussed with @jabauer and confirmed that we're only working from the main spreadsheet, and will ignore the people and places sheets - that data will be filled in once we're working with the project team.

I'll consolidate the import stories into a single story for people, places, and books, and create separate issues for the added functionality relating to people and viaf.

**Comment by rlskoeser** [comment]
Questions and notes on the import logic so far:
- am I correct to assume all books in the spreadsheet are extant?
- am I correct to assume NYSL catalogue information should be marked as current for all books?
- are there any cases with multiple authors, editors, or translators?  (If so, please provide a few examples or tell me how they are structured)
- in some cases 'annotated' column has notes; should these be preserved somewhere?
- the spreadsheet has a column for subjects but I don't see any subjects that have been added; is that correct?
- which field or fields should be used for physical description? (Physical size? Number of Pages? Type of Volume? NYSL Description?)
- I need to link the imported books to NYSL, so I'm going to create an initial "Owning Institution" record for NYSL.  When you see it in test, let me know if you want it modified in some way.  (Or you can always change it to your liking once we move to production).
- Some fields don't map exactly or seem relevant; if you want these added to a notes field somewhere, please let me know.  (This might be more obvious after reviewing a test import.)

**Comment by rlskoeser** [comment]
New question, after a test run of the current import script: some publication years are missing entirely and others have date ranges (40 books total with publication year problems).  Here are the ones I'm seeing that are causing errors: `1617-1621`, `1603-04.`, `1659 [i.e. 1658`.

Does publication year need to be made optional?  And how should I handle the date ranges above?

**Comment by rlskoeser** [comment]
I ran the preliminary data import script on the test site so you can use it to test the other features and review what it's doing so far to help answer the questions.

Errors are almost all related to the date issue flagged above.  It also looks like we have one book title longer than the database current limit of 255 characters; I can adjust the database to accommodate that.

Here's the full script output:
```
/var/deploy/winthrop-django/winthrop-django-develop/env/lib/python3.5/site-packages/django/db/backends/mysql/base.py:110: Warning: (1265, "Data truncated for column 'title' at row 1")
  return self.cursor.execute(query, args)
Error on import for Utriusque cosmi maioris scilic: invalid literal for int() with base 10: '1617-1621'
Error on import for Mecometrie de leymant.: invalid literal for int() with base 10: '1603-04.'
Error on import for A vindication of the Animadver: invalid literal for int() with base 10: ''
Error on import for Discours admirables: invalid literal for int() with base 10: ''
Error on import for De pulvere sympathico: invalid literal for int() with base 10: ''
Error on import for The works of that famous chiru: invalid literal for int() with base 10: ''
Error on import for : invalid literal for int() with base 10: ''
Error on import for : invalid literal for int() with base 10: ''
Error on import for Congeries Paracelsica : invalid literal for int() with base 10: ''
Error on import for A commentary upon the divine r: invalid literal for int() with base 10: ''
Error on import for Les provinciales, or, The myst: invalid literal for int() with base 10: ''
Error on import for Della magic'arte: invalid literal for int() with base 10: ''
Error on import for Perspectiva: invalid literal for int() with base 10: ''
Error on import for Apologia: invalid literal for int() with base 10: ''
Error on import for Christian Oeconomie: invalid literal for int() with base 10: ''
Error on import for Luthers fore-runners: invalid literal for int() with base 10: ''
Error on import for An Essay Concerning Adepts: invalid literal for int() with base 10: ''
Error on import for Traicté de la vraye, unique, g: invalid literal for int() with base 10: ''
Error on import for : invalid literal for int() with base 10: ''
Error on import for Polemonis, Himerii, et aliorum: invalid literal for int() with base 10: ''
Error on import for Basilica antimonii: invalid literal for int() with base 10: ''
Error on import for Opticae libri quatuor: invalid literal for int() with base 10: ''
Error on import for Solis e puteo emergentis . . .: invalid literal for int() with base 10: ''
Error on import for : invalid literal for int() with base 10: ''
Error on import for Goclenius heautontimorumenos: invalid literal for int() with base 10: ''
Error on import for Ephemeris perpetua: invalid literal for int() with base 10: '1628-1630'
Error on import for New Kochbuch: invalid literal for int() with base 10: ''
Error on import for Arithmeticae libri duo: invalid literal for int() with base 10: ''
Error on import for Tractatus arithmetici partium: invalid literal for int() with base 10: ''
Error on import for Mesolabii expositio.: invalid literal for int() with base 10: ''
Error on import for Polygraphica: invalid literal for int() with base 10: ''
Error on import for Le cose maravigliose: invalid literal for int() with base 10: ''
Error on import for Von dem rechten wahren philoso: invalid literal for int() with base 10: ''
Error on import for Oculus: invalid literal for int() with base 10: ''
Error on import for Vita honesta: invalid literal for int() with base 10: ''
Error on import for Mount Ebal Levell'd: invalid literal for int() with base 10: '1659 [i.e. 1658'
Error on import for Disconnected Material: invalid literal for int() with base 10: ''
Error on import for Commentarius: invalid literal for int() with base 10: ''
Error on import for Opticae libri quatuor: invalid literal for int() with base 10: ''
Error on import for Vertoogh: invalid literal for int() with base 10: ''
Imported content:
    308 books
    75 places
    249 people
    289 publishers

40 errors
```

**Comment by bwhicks** [comment]
Hi, chiming in on this again. Further work on the import script aside, we do need input on the two issues Rebecca raised above to complete this.

 @christianflow , whenever you and the team have a chance.

**Comment by christianflow** [comment]
I have addressed all the errors in the above script output given by Rebecca. There are a couple of examples (e.g. Rosius, Jakob, row 269) where a range of years in form xxxx-yyyy is given. Likewise, in the case, e.g., of Schottenius (row 284) there is no date given: the information given there is currently "nd." All other errors in the output have been emended into a form that should present no problem for the import. 

To Ben's question: I have reviewed the blanks for place of publication and publisher name to get a sense of the issue. Where possible I have added information, such that in those two columns one can assume that the semantics of notations like nd, s.d., s.n., sn, and blank are all the same: i.e., we have no information for the given field. The best thing to do, if possible, will be to rig the script so that for any of those items, it inserts a BLANK SPACE into the database. This approach should work as well for Author, Editor, and Translator.

**Comment by bwhicks** [comment]
Thanks for the input on this. I've done the equivalent of a blank space in the DB for uncertain/unknown authors and loaded in the lastest pull using the script. It should have pulled in the data from a pull of the spread sheet as of 5:30 or so this evening.

It also add geonames id to places (including therefore lat and long), as well as birth/death dates if VIAF found the person and provided them.

For multi year ranges, publication year of a book is pegged to the first date in the range and then the Notes field has the further info attached.

**Comment by christianflow** [comment]
I like this, Ben. Looks like everything is working. One thing I'd like to do for the ultimate import is to go through the spreadsheet and get the Short Titles right/in order, make sure the notes (incl. pages of interest where marginalia occur) are as clean as possible.

**Comment by christianflow** [comment]
Short titles have been input, and notes have been cleaned up to the extent possible
