### ISSUE TITLE
user permissions

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#33]
As an admin, I want to edit user and group permissions so I can manage project team member access within the system.

**Comment by rlskoeser** [comment]
This is a feature that we basically get for free with Django, but I wanted to make sure you know that you have it and how to use it.  If you have the necessary permissions, you should see an 'Authentication and Authorization' section with links for users and groups on the main admin dashboard.    Feel free to create a test user account so you can try out managing permissions, and see what the admin looks like to someone with fewer permissions (e.g., log into the test site in a different browser or in an incognito window so you can manage permissions with your main account and see what changes with the other account).

**Comment by christianflow** [comment]
Looks good! Created a "data editor" account named "grollege." Then deleted.
