### ISSUE TITLE
Switch to mezzanine version of grappelli

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#38]
We will eventually want CMS functionality on the public facing website, and it seems to make sense to just use mezzanine across all our projects - but mezzanine has a different version of grappelli, so we should probably switch to that version sooner than later, so we don't end up changing the interface on our project team and so any work we're doing that are specific to grappelli styles in the admin actually match the version we'll be using.

If possible - install mezzanine + its version of grappelli, but don't actually enable any of the mezzanine functionality since we don't need or want it yet.  (Hopefully by just not including mezzanine apps in django installed apps; possibly by suppressing them via mezzanine admin customization, if necessary.)

**Comment by rlskoeser** [comment]
@bwhicks it looks to me like maybe we could just switch from `grappelli` to `grapplli_safe` for now, and not add all of mezzanine.  What do you think?

**Comment by bwhicks** [comment]
@rlskoeser That's what I was thinking while walking to the car. That sounds like a plan.

**Comment by bwhicks** [comment]
Closing this because we're using grappelli rather than mezzanine's theme going forward
