### ISSUE TITLE
annotation + anchor text & translation

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#41]
As an annotation data editor, I want the option to enter the anchor text and anchor text translation so that I can describe the content that the marginalia references.

**Comment by bwhicks** [comment]
Making a note here to document (which I missed) that languages need to be associable with anchor_text also. (Potentially because text could be in two languages, as per #49 with annotation when Winthrops  annotate in two languages).

**Comment by bwhicks** [comment]
@christianflow We're looking at any places where the database schema for annotations can be simplified pre-production and wanted to clarify: Is it necessary that anchor text for an annotation be able to capture more than two languages (analogous to #49)? 

I believed that this was part of desired functionality but think I may have assumed.

**Comment by christianflow** [comment]
Hey Ben, This is a great question. I think it not unlikely that in the life of the project we'll encounter a situation where the anchor text shows more than two languages: the thing that comes to mind are school-texts or language-manuals, where there is a language being explicated in a second-language, perhaps also with parallel examples from a third or fourth. Bottom line: it would be good to have the capacity to tag a few different languages for an anchor text.

**Comment by christianflow** [comment]
Awesome stuff. Thanks guys!
