### ISSUE TITLE
annotation + optional fields

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#42]
As an annotation data editor, I want the option of leaving all fields blank so that I can accurately describe non-verbal annotations or annotations that don't relate to anchor text.

**Comment by rlskoeser** [comment]
I think we pretty much get this for free with annotator.js as well.  We'll just need to make sure we keep all the additional fields we add optional (and removable!) as well.

**Comment by christianflow** [comment]
Great stuff.
