### ISSUE TITLE
digitized books

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#48]
As an admin, I want to associate digitized books with the book record in the system so that I can connect the digitized version with the information about the book and so I can document marginal annotations on the pages.

**Comment by rlskoeser** [comment]
It occurred to me that this functionality was sort of implied and should be made explicit, because we definitely should test it.  I'm not certain if we'll be able to automatically link up imported IIIF volumes to existing book records - but since there are only ~50 right now, it's probably workable if we need to do it manually.

**Comment by bwhicks** [comment]
Spoke with Jon Stroop's group for Plum: manifests are in but still not batch loaded. It should be imminent though, and if not, I will follow up.

**Comment by bwhicks** [comment]
This one doesn't need testing per se, but the collection is digitized and fully imported on the development server (or will be, once this is loaded).

They don't yet have NYSL call numbers, so are not automatically associated.

**Comment by rlskoeser** [comment]
@bwhicks is there any testing/review @christianflow should do here, or should we just consider it more of a chore and close it ourselves?

**Comment by bwhicks** [comment]
@rlskoeser, I believe this is simply a chore that can be closed, which I will do now.
