### ISSUE TITLE
add/edit publishers

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#5]
As a data editor, I want to add a new or edit an existing publisher so that I can track books by publisher in a standard way.

**Comment by mcmcmahon** [comment]
for existing there is a drop-down menu, which is great. Easy enough to add with the plus sign next to Publisher, though in the drop down it is then not alphabetical but at the very bottom of the previously existing alphabetical list

**Comment by rlskoeser** [comment]
@mcmcmahon I think this is a limitation of django admin.  I tried it, and it looks like the newly added item shows up at the bottom of the list when you add it (and is also selected), but then if you reload the page it is alphabetized normally.

However, I'm going to go ahead and change the publisher lookup on the book edit form to use an autocomplete (and it's configured so you can search for partial text within the publisher name, not just the beginning of the name).  When you get a chance to test again, let me know if that works better for you (and if so, we probably want to update some other fields to work that way too, like looking up people for creators and book/person relationships).

**Comment by christianflow** [comment]
I've tested Rebecca's new auto-complete for publisher lookup in the book edit form and found it to be really helpful. If it would be possible to implement this in other fields (e.g., looking up people for creators and book/person relationships) I'd certainly be in favor.

**Comment by bwhicks** [comment]
I grabbed the low-hanging fruit on this one. People are now generally lookup-able in the Book change form (and the from relationship form of Person, since there was no reason not to add it.)

**Comment by christianflow** [comment]
Dig it, Ben. This is wonderful. Thanks so much.
