### ISSUE TITLE
admin: Fix links for usability on admin

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/winthrop-django#54]
As an admin user, I want to view the admin site by default until there is a public facing site, with links to the iiif-books application so that I can navigate from a familiar interface.

**Comment by bwhicks** [comment]
Code now redirects to admin/login by default, then provides a button in the upper-right user menu that says 'View Digitized Books'  which links to the IIIF-viewer and annotations interface.

**Comment by christianflow** [comment]
This is perfect, guys. Love it. Very intuitive to get to the books and get to work. Many thanks!
