### ISSUE TITLE
annotation: revise annotation display

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/winthrop-django#56]
Per Xinyi Li (UX designer)'s suggestions:

* Consolidate translation and transcription fields closer to one another
* Have field titles persist or be noted in some way
* Relabel tag field as 'annotation type'
* Move new 'annotation type' field to same fieldset as annotation
* Highlight or otherwise color the outline of the autocomplete
* Autocomplete should open with browser focus for short fields
* Note to remind user that all fields are optional
* Annotation field order matches Django admin
* Relabel annotation author as just 'annotator' (to avoid confusion with author)

**Comment by christianflow** [comment]
Again, this might be something for Xinyi to have a look over, since for some of these (eg Annotation field order matches Django admin) I'm not quite sure what to be looking for or what per se to "test." This all seems to have been successfully completed, though there is still not a note to remind user that all fields are optional I think.

**Comment by xinyil** [comment]
**Annotation entering interface**

Observations
- Annotation transcription doesn't have its filed title 
- "annotation type" is at the bottom of list when completed entering. Should be the same order as in the annotation entering panel 
- Can you add a new annotation type through typing? Did not work for me when I tried to add one.
- instructions for doesn't go away when selected from the drop down (see image)
- displaying panel falls to the bottom, thus become not visible unless you scroll down

Suggestions
- change mouse arrow to hand when hovering the entering panel to indicate that it's draggable

**Comment by xinyil** [comment]
**Admin annotation editing interface**

- "annotator" filed tile is still "author"
- "anchor languages" becomes a required filed when trying to edit other fields and save
-  maybe move "Canvas" to the beginning or towards the end after "anchor language"

**Comment by rlskoeser** [comment]
FYI, we can't currently display the tags the way Xinyi recommends due to a limitation with annotator-marginalia and time constraints.  We'll take a look at this as we update winthrop annotation code for the derrida project, and if we figure out a fix we'll adapt and add it to this project.  I'll add an issue so we don't forget.

**Comment by rlskoeser** [comment]
@christianflow thanks for taking a look and thanks for the excellent suggestion that @xinyil test this, that was a good way to handle it.  Are you fine with Xinyi signing off on this one when we've made the changes she's recommended (and that we can quickly do at this point)?

**Comment by bwhicks** [comment]
@xinyil One note -- I've gotten the two stylistic changes (label for annotation text called well, 'text' and the hand for the annotator controls to convey movement). The one other thing we hadn't spoken to was adding tags that weren't in the list. In the end, the project wanted it to be a controlled vocab, so a tag not on the list will simply not be added on save.

**Comment by christianflow** [comment]
I'm fine with this too if Xinyi is! Thanks Xinyi, Rebecca, Ben!

**Comment by xinyil** [comment]
thanks for the clarification! There are 2 minor remaining questions:

- when hovering on a label in annotation interface, the cursor did turn into hand but it is not draggable. When hovering the blank space at top it is still an arrow although it's movable 
- subject field and annotator field in admin is reversed as they are in annotation panel

**Comment by rlskoeser** [comment]
@xinyil I've made the changes you mentioned (along with a few other small style tweaks) and updated the test site.

**Comment by xinyil** [comment]
The annotation entering panel can only be dragged vertically in Safari. In Chrome it works as expected.

Suggestion:
If the subject type is a controlled list, and you can not add new one in this interface, we might consider change this input into a dropdown and eliminate the text field to avoid confusion!

**Comment by bwhicks** [comment]
Closing per @xinyil verbal okay to @rlskoeser, suggestion moved to #65.
