### ISSUE TITLE
admin: revise annotation admin layout

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/winthrop-django#57]
Per suggestions from UX designer:

* Make annotation thumbnail first field and clickable
* Make tag json read only to avoid confusion or inadvertent changes
* Make sure the tag order is the same as the annotation interface
* If possible, allow users to add book change form for non-digitized editions

**Comment by christianflow** [comment]
Little hard to know what there is to test here.

**Comment by bwhicks** [comment]
from @xinyili in #56
Admin annotation editing interface
    "annotator" filed tile is still "author"
    "anchor languages" becomes a required filed when trying to edit other fields and save
    maybe move "Canvas" to the beginning or towards the end after "anchor language"

**Comment by christianflow** [comment]
I'm good with this if Xinyi is.

**Comment by xinyil** [comment]
- Make tag json read only to avoid confusion or inadvertent changes
I'm not clear on what this is referring to 

- The "Author" column should be named as "Annotator" https://test-winthrop.cdh.princeton.edu/admin/annotation/annotation/
- Rename "Tags" to "Annotation Type". Should we call it "Annotation Type(s)" at the other places when this name occurs? https://test-winthrop.cdh.princeton.edu/admin/annotation/

**Comment by bwhicks** [comment]
> * Make tag json read only to avoid confusion or inadvertent changes
> I'm not clear on what this is referring to

Sorry for any confusion on this. I marked extra_data as read only so that the tag data can't be inadvertently edited since it's all set in the annotator interface.

Author has been renamed to "Annotator" in the list view on the Django admin (c83643a)

Tags has been relabeled "Annotation Type" and will appear when plural as "Annotation Types" as appropriate. Django has a slot for both and knows when to use plural vs singular usually.
