### ISSUE TITLE
javascript regression on test site

### ISSUE THREAD

**Issue by christianflow** [Princeton-CDH/winthrop-django#59]
This just a note that I am finding some elements less intuitive than previously: for testing purposes, have been looking to add people and find eg that automatic VIAF look-up isn't taking place, and that when I go to add a From Relationship, it doesn't give me autocomplete with the names of people I have added (eg Forth Winthrop). This could just be a matter of me figuring out how things work, but wanted to flag it at the outset.

**Comment by rlskoeser** [comment]
@christianflow thanks for noting this.  We got caught by an issue in an updated version of one of our dependencies that broke the way javascript libraries were getting loaded (or not loaded), and it affected a lot of the dynamic functionality on the site.  We've corrected that, and you should see that things are behaving the way you expect them to.  Please check on the test site and close this once you've confirmed (or let us know if that's not the case!).

**Comment by christianflow** [comment]
This looks to be fixed.

**Comment by rlskoeser** [comment]
@christianflow I'm going to reopen this because I think you checked in production rather than test.

**Comment by christianflow** [comment]
Now tested on the test site; looks good!
