### ISSUE TITLE
add/edit owning institution

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#6]
As a data editor, I want to add a new or edit an existing owning institution so that I can document the current or previously known location of extant books.

**Comment by mcmcmahon** [comment]
C Flow  tested this on Win 145b--he added NYAM as prior owner. And we also observed that the Catalogues section can allow us to add previously owning institutions and the years they owned the book. J Rampling noticed that if we add that it owned the book from 2010 to 2009 the system still accepts this time travel.

**Comment by rlskoeser** [comment]
@mcmcmahon validation is pretty minimal right now in the database, I think just the unique values that we discussed over email at some point.  Anywhere like this where you run into something you want validated, please request it and we'll add it.

**Comment by rlskoeser** [comment]
Added validation on dates throughout the site.  (Note: allows same year to let you indicate a single year, but I don't know if that's documented anywhere or likely to come up.)

**Comment by christianflow** [comment]
I tested the validation for years and it would not let me add a second owning-year that antedated the first owning-year. It would allow two entries of the same year, as if ownership were for a single year. This is wonderful.
