### ISSUE TITLE
As an annotation editor, I want to take notes while I'm capturing and describing an annotation so I can document references or other information.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#66]
## Notes for testing
- the new notes field should be available on the editor on the page image view
- test that you can add a note and save, edit a note and save, reload the page and see the note
- check that the note also displays in the admin interface (can test here or as part of #67 ) 

## Notes for development
Add an optional text note field to the javascript annotation editor.

**Comment by stone-julia** [comment]
I selected a digital book, added a new annotation with a note. Saved and reloaded and it was still there. Then I edited the note, saved and reloaded it and it was still there.
