### ISSUE TITLE
As an annotation admin, I want a way to get from the annotation capture interface to the admin interface so that I can add structured footnotes to annotations.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#67]
## Notes for testing
- the footer of the annotation display in the margin on the page image view should have a link to the admin version of the same annotation: "edit in admin"
- annotation in the admin should also have a "view canvas on site" link to navigate from admin view to page image view

---
Add a link from the annotation card on the page image view to the django admin page for the annotation.  Should use django admin url to generate the link, but need a way to generate a link for newly created annotations once they are saved.

**Comment by stone-julia** [comment]
Tried the "edit in admin" link from test annotation and it worked. Then opened annotation in admin interface and tried "view canvas on site" link which also worked.
