### ISSUE TITLE
As an annotation admin, I want an easy way to associate footnotes with annotations so that I can document known references and other details.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#68]
## Notes for testing
- annotation edit form in the admin site should display a footnote section at the bottom
- notes are displayed towards the bottom of the form, to make it easier to convert unstructured notes into footnotes 
- testing adding a footnote and editing a footnote

--- 
Make footnotes available as an inline on the annotation admin edit form.

**Comment by rlskoeser** [comment]
Not a zero because annotation has a uuid rather than integer id, so a little adjustment was required.

**Comment by stone-julia** [comment]
When I opened my test annotation in the admin interface a footnote section was displayed at the bottom. I entered a test footnote annotation and saved it. When I reopened the test annotation my original footnote was there and a new window to add another footnote was displayed. I edited my original annotation, saved it, and reopened it.
