### ISSUE TITLE
As a user, I want to view a paginated list of books associated with the Winthrops so that I can browse the books they owned.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#69]
## Notes for testing
- books should be displayed with short title, author, year, and thumbnail if there is an associated digital edition
- pagination links should let you page through the results so you can see more books

Display title, author, year, thumbnail

**Comment by stone-julia** [comment]
Tested this feature by opening the book browse link sent by Rebecca K, and it is clearly working! All information displayed correctly and clearly, and even the thumbnails look great. 

For future versions it may be helpful to add an option to alter the number of columns in display (currently defaults to 2).
