### ISSUE TITLE
As a user, I want to change how the list of books is sorted so that I can browse the list by publication date or author.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#70]
## Notes for testing
- by default, books should be sorted alpha by author
- should be able to change to other available sort options
- paging through should preserve your current sort
- relevance sort should only be available when there is a keyword search term

## Notes for development

- Sort by publication date (oldest to newest or newest to oldest) 
- by author (default)

**Comment by stone-julia** [comment]
Tried to sort by author A-Z, author Z-A, year oldest-newest, year newest-oldest. All seem to be working perfectly and maintain the organization when going to next page or skipping several. Sort by relevance option appears, but is not select-able without a search term.
