### ISSUE TITLE
As a user, I want to filter the list of books by editor so that I can narrow the list based on editors I'm interested in.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#78]
## Notes for testing
On the first tab of the search form, you should see a list of editors associated with books and the count of books for each. Selecting a name should limit books to just those editors. Selecting multiple names should display all books associated with any of the selected editors.  Editor filtering should work in combination with other search options.

**Comment by jmrampling** [comment]
Works fine, for single and multiple editors, and in combination with date range. See my comment on the search-by-author user story, since this functions in the same way (including the problem with removing the publication date range).
