### ISSUE TITLE
add/edit books

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#8]
As a data editor, I want to add a new or edit an existing book so that I can document the publication data, annotation data, and other relevant details.

**Comment by christianflow** [comment]
This is looking good, but one thing I noticed is that if I added a new book abortively and then looked to delete it from the database, there is no way to delete when working from the Book-edit screen (i.e. where one can add/modify title, owner, year, etc). One has to click it in the book-list and then approve the deletion. It might be convenient to have also a "delete full book" option from the Book-edit screen.

**Comment by bwhicks** [comment]
On this one, I believe the functionality exists already if I am understanding the question correctly.

![screen shot 2017-03-01 at 11 59 47 am](https://cloud.githubusercontent.com/assets/17815297/23471282/cf2d4100-fe76-11e6-97bf-529cc8071c4b.png)
