### ISSUE TITLE
Template: header and footer

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/winthrop-django#86]
## zeplin
[L](https://zpl.io/V0y3veQ) / [M](https://zpl.io/boxwXgG) / [S](https://zpl.io/aB5X0eA)
## notes
- [x] footer should stick to the bottom
- [x] footer gradient should be correct & responsive
- [x] placement of logos and text in footer should be correct
- [x] footer should resize correctly
- [x] headers should resize correctly
- [x] headers should use the correct images for S/M/L [1x/2x]
- [x] overlap between header and main content should be correct (when there's an image)

**Comment by thatbudakguy** [comment]
it seems based on Zeplin that the only thing that really constitutes a "header" is the page title text, which is interesting because it also duplicates the big splash images on all pages that have a title. might just create a placeholder for the header for now.

**Comment by thatbudakguy** [comment]
Went with a PPA-style footer for now.

**Comment by dschlein** [comment]
Macbook 13 inch, chrome - footer: sticks to bottom but no gradient, placement of logos and text is correct; header: headers resize correctly, uses correct images, overlap between header and main content is correct
iPhone 6, safari -  footer: sticks to bottom but no gradient, lots of space between manicule, labels, Winthrop logo, and bottom "contact, home, etc.," placement of logos and text is correct, footer does not resize correctly - see above for iphone 6/safari "lots of space;" header: headers resize correctly, but smaller top books header is white, not bronze like the larger Books header below it, overlap between header and main content is correct

**Comment by thatbudakguy** [comment]
- gradient has been reinstated...don't remember why we took it off but it's back!
- color of header text has been fixed; nice catch @dschlein 
- footer sizing weirdness seems to be due to something in how iOS safari handles flexbox...added some fixes that I think resolved it.

**Comment by dschlein** [comment]
Macbook Pro, 13 inch, Chrome - gradient exists
iPhone 6 - gradient is there, color of text header has been fixed, footer size oddities have been fixed
