### ISSUE TITLE
Template: navigation

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/winthrop-django#87]
## zeplin links
[L](https://zpl.io/bzWmQ68) / [M](https://zpl.io/aXMBOLX)
## notes
- [x] transparent and overlapping header image on M/L but not S
- [x] should be responsive
- [x] mobile menu button should work
- hover/active states will be fixed in next round
- light/white version coming when I do the homepage

**Comment by dschlein** [comment]
Macbook Pro, 13 inch, Chrome - header is transparent and overlapping, header looks good here - fits
iPhone 6, Safari - header is transparent and overlapping, header looks good, mobile menu button works
