### ISSUE TITLE
edit books - inline edit for language, subject, owning institution

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#9]
As a data editor, when I’m editing a book I want to be able to associate languages, subjects, and owning institutions on the same page so that I don’t have to edit book information in multiple places.

**Comment by rlskoeser** [comment]
Note that owning institution is linked via catalogues, so that's how it's labeled on the book edit form.

**Comment by mcmcmahon** [comment]
This all works fine. Testing done on "The Wizard of Oz."
