### ISSUE TITLE
Template: books list

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/winthrop-django#92]
## zeplin links
[L](https://zpl.io/agZEgOV) / [M](https://zpl.io/VQYXNEm)
## notes
**this is just the base page - all of the details like search form, pagination, and search results are separate issues**
- template for search form is tracked on #95 
- template for a single search result is tracked on #94 
- template for pagination is tracked on #93 
- [x] header image should load correct size (1x/2x) and scale/be positioned correctly
- [x] search results should use two columns and collapse to one on mobile
- [x] pagination and form should appear in the right places for each screen size

**Comment by dschlein** [comment]
Macbook 13 in, Chrome, w/o retina display - search results display two columns correctly, pagination and form are the right size and in the right place
iPhone 6, Safari, w/o retina display - search results collapse into one column, but it does take a while to get to editor - you have to go through a bunch of authors, so the person searching needs to be extra persistent; language and annotator tabs are cut off, so you can't access them

**Comment by thatbudakguy** [comment]
Moved remaining issues with mobile to #119, since it's evident I need to create a separate component to handle search form presentation on small screens. Going to close this.
