### ISSUE TITLE
Template: book list view single result

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/winthrop-django#94]
## zeplin links
[L](https://zpl.io/agZEgOV) / [M](https://zpl.io/VQYXNEm) / [S](https://zpl.io/a8KMQ9K) - single result in the list
## testing notes
- preview image should be the right size and position
- correct info should be displayed on card, including labels
- clicking anywhere on the card should go to detail view
- hovering on the card should show the full title as a tooltip
- arrangement and sizing of cards should change responsively

**Comment by thatbudakguy** [comment]
@xinyil do you have any ideas for what to do about long titles? we're already using the "short title" but it seems that some short titles aren't so short...I could try limiting it to a few words maybe? I think the issue is that there are also a lot of long words (german/latin) which forces it to wrap quite a bit

mostly a problem on M/S since the cards are long enough on L that it doesn't become an issue.

<img width="430" alt="screen shot 2018-07-16 at 11 11 55 am" src="https://user-images.githubusercontent.com/4924494/42766701-21f3ccf8-88e9-11e8-8de4-a6acd83b112a.png">

**Comment by thatbudakguy** [comment]
try using some combination of:
- django truncation
- [text-overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)

also add a title attr so full title is visible on hover

**Comment by thatbudakguy** [comment]
per @xinyil need to make these not white and also align the images left rather than to the right edge of the card.

**Comment by thatbudakguy** [comment]
realigned images, changed card background, added title attribute, truncated length. there is one edge case (the "Ander Theil" book), but I'm happy otherwise.

**Comment by dschlein** [comment]
Macbook Pro, 13 in, chrome - correct size and position, correct info displayed, clicking from anywhere on card gives detail view, hovering shows full title in tooltip, 
Iphone 6, Safari - Ander Theil, Card 5: the label cuts off on the card, correct size and position, correct info displayed, clicking from anywhere on card gives detail view, you can't hover on a phone

**Comment by thatbudakguy** [comment]
I think this is OK since Mr. "Ander Theil" is an edge case. We might want to ask the project team if they're comfortable altering that title slightly so that the ellipsis isn't part of the word, which would allow django to break it up more naturally. @rlskoeser do you think that's an OK thing to ask?

**Comment by rlskoeser** [comment]
I think we're going to want the team to review the content and make sure things look the way they want anyway, so this sounds reasonable to me.

**Comment by thatbudakguy** [comment]
OK, I'll close this then.
