### ISSUE TITLE
Template: site search

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/winthrop-django#97]
## zeplin links
[L](https://zpl.io/VYBOL1J) / [M](https://zpl.io/VxYN48E) / [S](https://zpl.io/aB5X4me)
## notes
- [x] should push down the rest of the page, a la derrida
- [x] should stack correctly on mobile
- [x] select behavior should work correctly
- [x] should autofocus the search field when it is opened

**Comment by dschlein** [comment]
On Iphone 6, Safari: the pushdown isn't working - the top menu covers up the search; stacks correctly; book selection works; when the search field is opened, it doesn't autofocus
Macbook Pro, 13 in, Safari - pushdown works, the book selection menu appears, autofocus works
Macbook Pro, 13 in, Chrome - pushdown works, the book selection menu appears, autofocus works
Macbook Pro, 13 in, Firefox - pushdown works, autofocus works, book selection menu appears

**Comment by thatbudakguy** [comment]
It looks like there's a bug in the semantic UI "push" behavior for sidebars on iOS. Using the safari devtools, if I emulate any iOS device, the sidebar will appear but won't "push" the rest of the page. This doesn't happen on OSX Safari; only on any iOS device.

I was able to get it to behave correctly by commenting out two lines:
```css
.ui.visible.overlay.sidebar ~ .fixed,
.ui.visible.overlay.sidebar ~ .pusher {
  /* -webkit-transform: none !important; */
  /* transform: none !important; */
}
```
couldn't replicate the "not autofocusing the text field" bug using the iOS emulator, unfortunately, so I think we'll have to leave that one alone.

**Comment by dschlein** [comment]
Macbook Pro, 13 in, Chrome - pushes down rest of page
iPhone 6, Safari - search pushes down rest of page; stacks correctly, autofocus works - but I can only tell that it works because the term 'search' turns from black to gray, I still have to click on the search text box to get my keyboard to open up so I can type;
